In [1]:
import numpy as np
from __future__ import print_function, division
import math


https://towardsdatascience.com/l1-and-l2-regularization-methods-ce25e7fc831c

$\alpha$ in L1, L2

https://onlinecourses.science.psu.edu/stat857/node/158

In [26]:
%%latex
\begin{equation*} \textrm{Lasso subject to:} \sum_{j=1}^p |\beta_j| < c. \end{equation*}
\begin{equation*} \textrm{Ridge subject to:} \sum_{j=1}^p (\beta_j)^2 < c. \end{equation*}

<IPython.core.display.Latex object>

In [31]:
class l1_regularization():
    """ Regularization for Lasso Regression """
    def __init__(self, alpha):
        self.alpha = alpha
    
    def __call__(self, w):
        return self.alpha * np.linalg.norm(w)

    def grad(self, w):
        return self.alpha * np.sign(w)


Signature: np.linalg.norm(x, ord=None, axis=None, keepdims=False)  
http://blog.csdn.net/lanchunhui/article/details/51004387

L1, L2 norm  
- http://mathworld.wolfram.com/L2-Norm.html
* http://mathworld.wolfram.com/L1-Norm.html

In [16]:
print (abs(-4)**2+abs(9)**2)**0.5
print np.linalg.norm([-4,9])

9.8488578018
9.848857801796104


In [17]:
print (abs(4)+abs(9))
print np.linalg.norm([4,9], ord=1)

13
13.0


___

https://www.cnblogs.com/xinchrome/p/5043480.html  
np.sign  
返回数组中各元素的正负符号，用1和-1表示

In [30]:
np.sign([5,2,-500,3,-2])

array([ 1,  1, -1,  1, -1])

In [24]:
np.linalg.norm([1,2,3,4])*5

27.386127875258307

In [72]:
a = l1_regularization(5)
print a([1,2,3,4])
print a.grad([1,2,3,4])

27.386127875258307
[5 5 5 5]


In [71]:
w=np.array(np.random.randint(-5,10, size=6)).reshape(-1,2)
w

array([[-3,  2],
       [-1,  3],
       [ 4, -4]])

In [73]:
a(w)

37.080992435478315

___

In [32]:
class l2_regularization():
    """ Regularization for Ridge Regression """
    def __init__(self, alpha):
        self.alpha = alpha
    
    def __call__(self, w):
        return self.alpha * 0.5 *  w.T.dot(w)

    def grad(self, w):
        return self.alpha * w

In [42]:
a=l2_regularization(7)

In [53]:
w=np.array(np.random.randint(-5,10, size=6)).reshape(-1,2)
w

array([[ 5, -3],
       [ 2,  0],
       [ 6,  2]])

In [54]:
w.T

array([[ 5,  2,  6],
       [-3,  0,  2]])

In [59]:
w.T.dot(w)*7*0.5

array([[227.5, -10.5],
       [-10.5,  45.5]])

In [60]:
a(w)

array([[227.5, -10.5],
       [-10.5,  45.5]])

In [62]:
a.grad(w)/7

array([[ 5, -3],
       [ 2,  0],
       [ 6,  2]])

___

https://en.wikipedia.org/wiki/Elastic_net_regularization

In [65]:
class l1_l2_regularization():
    """ Regularization for Elastic Net Regression """
    def __init__(self, alpha, l1_ratio=0.5):
        self.alpha = alpha
        self.l1_ratio = l1_ratio

    def __call__(self, w):
        l1_contr = self.l1_ratio * np.linalg.norm(w)
        l2_contr = (1 - self.l1_ratio) * 0.5 * w.T.dot(w) 
        return self.alpha * (l1_contr + l2_contr)

    def grad(self, w):
        l1_contr = self.l1_ratio * np.sign(w)
        l2_contr = (1 - self.l1_ratio) * w
        return self.alpha * (l1_contr + l2_contr) 

In [66]:
a=l1_l2_regularization(0.5)

In [67]:
w

array([[ 5, -3],
       [ 2,  0],
       [ 6,  2]])

In [68]:
a(w)

array([[10.33294022,  1.83294022],
       [ 1.83294022,  3.83294022]])

In [69]:
a.grad(w)

array([[ 1.5 , -1.  ],
       [ 0.75,  0.  ],
       [ 1.75,  0.75]])